### ISSUE TITLE
Update mysql-binlog-connector

### ISSUE THREAD

**Issue by walro** [twingly/ecco#18]
0.3.1 released, we use 0.2.4.

https://github.com/shyiko/mysql-binlog-connector-java/blob/master/changelog.md

> Support for "non blocking" mode (equivalent to running mysqlbinlog without --stop-never)

Maybe that could help us somewhere?

**Comment by walro** [comment]
0.3.2 has been released now too.

> Fractional seconds deserialization on MySQL 5.6.4+ (#103).

Looks like a good thing to have.

**Comment by dentarg** [comment]
There has been many releases, [right now 0.13.0 is the latest](https://github.com/shyiko/mysql-binlog-connector-java/blob/9e8c0aa2685fa182e31abc61c9eeccf24425e791/changelog.md). We should probably try to keep up with upstream.

**Comment by dentarg** [comment]
Scrolled the changelog, notable stuff:

* Fixed: race condition that could result in duplicate events to be emitted on reconnect
* support for MySQL JSON type
* TIME/DATETIME/TIMESTAMP microseconds precision support
* [MySQL heartbeat](https://www.percona.com/blog/2011/12/29/actively-monitoring-replication-connectivity-with-mysqls-heartbeat/) support
