### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by walro** [twingly/ecco#2]
We need to test at least the following:
- Insert some rows
- Update some rows
- Delete some rows
- Ensure that database/table information is correct
- Ensure that we can handle file rotations
- Set and get public properties

**Comment by roback** [comment]
The `mysql2` gem cannot be used for this as it uses a C extension. I'll try with https://rubygems.org/gems/jdbc-mysql and see if that works. (for creating/dropping tables and inserting/deleting/updating rows)
