### ISSUE TITLE
Update Vagrant box to ubuntu/bionic64

### ISSUE THREAD

**Issue by walro** [twingly/ecco#39]
Trusty (14.04) is EoL. Move to latest LTS, Bionic (18.04).

A problem is that we only support MySQL 5.5/5.6, while Bionic ships with MySQL 5.7.

See https://github.com/twingly/ecco/blob/e83cbfcffbb09833f42d6bf570ccd0c0ae903407/Vagrantfile#L4

**Comment by dentarg** [comment]
I think we can use Docker here :)

**Comment by walro** [comment]
Have you found a bionic image with MySQL 5.6?

**Comment by dentarg** [comment]
Nope... but do we need it to be bionic?

**Comment by dentarg** [comment]
https://hub.docker.com/_/mysql, https://github.com/docker-library/mysql hasn't made the move to buster yet but I assume they do before [stretch is unsupported](https://en.wikipedia.org/wiki/Debian_version_history#Release_table) :)

**Comment by dentarg** [comment]
There are also images based on [Oracle Linux](https://en.wikipedia.org/wiki/Oracle_Linux): https://hub.docker.com/r/mysql/mysql-server/, https://github.com/mysql/mysql-docker

**Comment by walro** [comment]
> Nope... but do we need it to be bionic?

Not really :) I think the main goal is 5.6 on something that's not EoL.
