### ISSUE TITLE
MySQL 8.0 support

### ISSUE THREAD

**Issue by walro** [twingly/ecco#41]
Seeing that Ubuntu has dropped MySQL 5.6 from Xenial (16.04) and onwards it might be a good idea to start officially supporting MySQL 5.7 and 8.0.

AFAIK there are no known stoppers for 5.7, so hopefully it's fairly straight-forward.

Edit: I added in MySQL 8.0 here
Edit2: MySQL 5.7 now officially supported as of 0.8.0

**Comment by walro** [comment]
Probably smart to look at #45 while at it.

**Comment by walro** [comment]
Changed the title as we now support 5.7, released with [0.8.0](https://github.com/twingly/ecco/blob/b5f379c3bb5c965b371daa3745e42ac0508dad97/CHANGELOG.md#v080-2020-10-23).

**Comment by Chrizpy** [comment]
As mentioned in https://github.com/twingly/ecco/pull/52, this PR resolves this issue.
