### ISSUE TITLE
Ensure that we handle "on_row_event" before "on_save_position"

### ISSUE THREAD

**Issue by walro** [twingly/ecco#5]
I think we do now, but we need tests to confirm it and ensure that we don't break it in the future.

**Comment by walro** [comment]
https://github.com/shyiko/mysql-binlog-connector-java/blob/7e30439ea14e39d4a78d6d3673369b1dfb7e3ad0/src/main/java/com/github/shyiko/mysql/binlog/BinaryLogClient.java#L833-L848

So whatever order the Java for-loop does it in is what we'll end up with I guess?

**Comment by walro** [comment]
It's a [LinkedList](https://github.com/shyiko/mysql-binlog-connector-java/blob/7e30439ea14e39d4a78d6d3673369b1dfb7e3ad0/src/main/java/com/github/shyiko/mysql/binlog/BinaryLogClient.java#L117) and I found this: http://stackoverflow.com/a/4767638 so I guess that we should add the `on_row_event` listener first.

**Comment by roback** [comment]
``` ruby
  describe "#on_row_event, #on_save_position" do
    context "when a row is inserted" do
      let(:actual_event_order) do
        event_order = []
        subject.on_row_event { |_| event_order << :on_row_event }
        subject.on_save_position { |_, _| event_order << :on_save_position }

        subject.start_in_thread

        DatabaseHelper.insert(table_name, mysql_row)

        sleep 0.1 while event_order.count < 4
        event_order
      end
      let(:expected_event_order) { [ :on_row_event, :on_save_position ] }

      it "should receive the events in correct order" do
        expect(actual_event_order).to eq(expected_event_order)
      end
    end
  end
```

```
Failures:

  1) Ecco::Client#on_row_event, #on_save_position when a row is inserted should receive the events in correct order
     Failure/Error: expect(actual_event_order).to eq(expected_event_order)

       expected: [:on_row_event, :on_save_position]
            got: [:on_save_position, :on_save_position, :on_save_position, :on_row_event]

       (compared using ==)

       Diff:
       @@ -1,2 +1,2 @@
       -[:on_row_event, :on_save_position]
       +[:on_save_position, :on_save_position, :on_save_position, :on_row_event]

     # ./spec/integration/client_spec.rb:80:in `block in (root)'
```

**Comment by walro** [comment]
From your test and from the LinkedList knowledge we now have attained I am certain we should register our `row_event` listener before our `save_position` listener. It would also be interesting to understand why we see four event (3 save followed by 1 row).

**Comment by roback** [comment]
Looks like mysql adds `BEGIN` (QueryEvent) and `COMMIT` (called XidEvent, [explained here](https://github.com/shyiko/mysql-binlog-connector-java/blob/671c7e8cebeec61487dabb0c12f728b51916753a/src/main/java/com/github/shyiko/mysql/binlog/event/EventType.java#L98-L103)) around each insert. The first `:save_position_event` is triggered by the `ROTATE` event (I have no idea why the `ROTATE` is triggered though), end the second `:save_position_event` is caused by a `BEGIN` statement which is added before each query apparently.

I added a logger to sequel and added a event listener which just prints each event.

``` shell
  #on_row_event, #on_save_position
    when a row is inserted
I, [2015-11-19T10:52:25.240000 #60842]  INFO -- : (0.001000s) DROP TABLE IF EXISTS `ecco_test_table`
I, [2015-11-19T10:52:25.245000 #60842]  INFO -- : (0.003000s) CREATE TABLE `ecco_test_table` (`id` integer PRIMARY KEY AUTO_INCREMENT, `column1` varchar(255))
RotateEventData{binlogFilename='mysql-bin.000150', binlogPosition=8107}
-------------
FormatDescriptionEventData{binlogVersion=4, serverVersion='5.5.46-0ubuntu0.14.04.2-log', headerLength=19}
-------------
QueryEventData{threadId=26379, executionTime=0, errorCode=0, database='ecco_test', sql='BEGIN'}
-------------
TableMapEventData{tableId=619, database='ecco_test', table='ecco_test_table', columnTypes=3, 15, columnMetadata=0, 255, columnNullability={1}}
-------------
I, [2015-11-19T10:52:25.257000 #60842]  INFO -- : (0.002000s) INSERT INTO `ecco_test_table` (`column1`) VALUES ('a value')
WriteRowsEventData{tableId=619, includedColumns={0, 1}, rows=[
    [1, a value]
]}
-------------
XidEventData{xid=57621}
-------------
[:on_save_position, :on_save_position, :on_row_event, :on_save_position]
I, [2015-11-19T10:52:25.262000 #60842]  INFO -- : (0.002000s) DROP TABLE `ecco_test_table`
      should receive the save event after the row event
```

**Comment by roback** [comment]
Commented out the `FLUSH BINARY LOGS` query in DatabaseHelper but i'm still receiving the rotate event.

This could be a clue :)

https://github.com/shyiko/mysql-binlog-connector-java/blob/671c7e8cebeec61487dabb0c12f728b51916753a/src/main/java/com/github/shyiko/mysql/binlog/BinaryLogClient.java#L646
