### ISSUE TITLE
Trying to connect to non-existent position behaves strange?

### ISSUE THREAD

**Issue by walro** [twingly/ecco#8]
I think I had troubles with this today. I tried to connect (using Bruce) to a file on Jon that had been deleted. It behaved weirdly, I got stuck in some sort of re-connect loop. A first step is to add a test for it.

**Comment by walro** [comment]
I have reported this upstream.

https://github.com/shyiko/mysql-binlog-connector-java/issues/37

**Comment by dentarg** [comment]
> I have reported this upstream.

URL?!
